### PR TITLE
Add options `replace_external_path` / `replace_output_path` to no lon…

### PR DESCRIPTION
**Pull request by lummax**
…ger require symlinks

### CODE REVIEW

**Comment by cpsauer** [comment]
Hey, Lukas! Good to hear from you. Thanks for your PR--and all the ways you've helped make this project better.

I know we'd discussed this some, way back in #14. Lots of the other things we discussed there have now happened, thanks to the good efforts of you and others--including a robust set of features around header extraction and external source files.

Focusing on some high level things for tonight.
[It got quite late my time, unfortunately, by the time I was able to get to this.] 
- So I understand: What motivates people to need to turn off those symlinks?
  - [I'm not against it. We just haven't needed it, and I want to understand the root need that's motivating the additional implementation complexity and interface.]
- I think getting this robust is going to be a bit subtle; it's harder getting things to work when the workspace root doesn't mirror the compilation environment.
  - As an example: Looking quickly back at 14, there's the `-Ibazel-out/<path>` case. And glancing at a compile_commands.json in front of me, I see an `-isystemexternal/<...>`. I'm sure there are more of these cases, including on Windows, and I'd need you to get them all.
  - We'll also need to take care to not break other key features, like, `_file_is_in_main_workspace_and_not_external` and hitting bazel's .d dependency cache under clang/gcc. There's also the case of file paths being absolute on Windows, and with varying separators.
  - That isn't an exhaustive list, I'm sure; we'd be changing a pretty fundamental, simplifying assumption here, and that's going to need some additional care. Writing this out made me realize that this is even trickier than I'd thought.
 
^ Given the above, I think we'll want to be pretty convinced this is needed and robust before we'd merge. I am probably going to need to ask you to do most of that work and maintainance. Is that worth it? Offhand, I'm tempted to try to talk you into just having the symlinks, especially if the use case is the temporary migration you'd mentioned in #14, but I could be missing something. Hopefully that's not too frustrating; I really appreciate your efforts and am looking forward to your reply.

Cheers,
Chris

--- 
[We shouldn't let these distract from the high level discussion, but here are notes about some more minor things that occurred along the way, so I don't forget them.]

- Maybe we shouldn't gitignore entries when their addition is disabled by a flag? e.g. external and bazel-*.
- Thoughts on leaning toward automatically configuring, like noted in 14? For example, we could detect if bazel-out exists -- and automatically apply that replacement if it does not? 
- Maybe let's consistently detect windows one way or another. Doesn't matter to me whether that's platform.system or os.name. (Also, minor, but import position.) Similar consistency note with _call_bazel.
- If we change the assumptions here, we should take a crack at updating the comments that rely on them. That'll also help find the cases we've broken.

**Comment by lummax** [comment]
Hey Christopher, 

I was delighted to see all the improvements now that I got some time to work on the `compile_commands.json` generation for us. Great work :+1: 

> So I understand: What motivates people to need to turn off those symlinks?

It is mainly Windows support and the inability of various tools there to copy with symlinks. Multiple colleges noticed that even the Windows Explorer search feature will follow symlinks and possibly end up in a symlink loop. Same for some indexing/search implementation for IDEs or command line search utilities. So to keep the Windows people happy we got rid of all bazel symlinks.

> I think getting this robust is going to be a bit subtle; [...] And glancing at a compile_commands.json in front of me, I see an -isystemexternal/<...>. I'm sure there are more of these cases, including on Windows, and I'd need you to get them all.

Yes, I am afraid you are right here. I'm not sure we can find them all, especially for esoteric compilers / configurations. But I'll try my best to find some more cases and add them.

> We'll also need to take care to not break other key features, like, _file_is_in_main_workspace_and_not_external and hitting bazel's .d dependency cache under clang/gcc.

Yes. I would hope that this remains an opt-in feature. We could even name the flags `experimental_...` to make sure users know there are caveats.

>  I am probably going to need to ask you to do most of that work and maintainance. Is that worth it?

Happy to do it, just ping me on related issues.

> Offhand, I'm tempted to try to talk you into just having the symlinks, especially if the use case is the temporary migration you'd mentioned in https://github.com/hedronvision/bazel-compile-commands-extractor/issues/14, but I could be missing something. 

I personally am all in for symlinks. But unfortunately that is not my call because of the mentioned Windows problems. The "temporary" migration will continue for some time. And I guess the Windows problems will remain valid after that.

I'll get back to this PR next week and push some updates.

**Comment by cpsauer** [comment]
> So to keep the Windows people happy we got rid of all bazel symlinks.

Oh, very interesting, this need on Windows. Thank you for explaining what's motivating this! For my learning, could I ask you to expand a little more? 
- Is it that these Windows tools are just treating junctions like normal directories, and therefore searching/copying their contents?
  - [I'd have guessed, perhaps, that people might want to automatically search/index their external and generated code. I'm always a little bummed that VSCode doesn't, e.g., automatically quick open through symlinks on other platforms.]
  - What breaks when copying something containing a junction, if not a deep copy?
- I'd also love to understand how one ends up in a junction loop on Windows with Bazel. (I'm asking only because I've failed to imagine how Bazel would construct one, but I believe you.)

> especially for esoteric compilers / configurations

I think we need only target msvc and gcc/clang flags here. This is making me wonder, if you think the need is Windows-focused--maybe the flag should be, too? Up to you. It's possible there's also a more general way to structure the replacement.

Really, though, I think we'll need this to be very clearly solid to merge in, given the complexity of removing the simplifying assumption that bazel's commands can apply, almost unchanged, to the workspace. I don't think we should merge experimental-and-broken; and I want to make sure I'm being as up front about that as possible. And while I'm concerned about how hard it might be (see also #30), I really appreciate your identifying the need and dedication to chasing it down. Good luck!

Cheers!
Chris

**Comment by lummax** [comment]
> Is it that these Windows tools are just treating junctions like normal directories, and therefore searching/copying their contents? 

I actually did not dig into this.

> I'd also love to understand how one ends up in a junction loop on Windows with Bazel. (I'm asking only because I've failed to imagine how Bazel would construct one, but I believe you.)

Now that you are mentioning it, this might actually be our fault: We have a `build/` directory in the workspace root that contains generated files from our legacy build system. I configured `bazel` do create the convenience symlinks below `build/` to keep the workspace root as uncluttered as possible. But I also had to `export_files()` some files below `build/` as they were generated by the legacy build-system. That resulted in the symlink cycle.

Thank you for that insight :)

In my mind this a use case the commands extractor should not support. This is a mis-use of `bazel` to some extent. I operated under the assumption that everyone will run into this on windows. Closing this PR :)

**Pull request closed without merging**
